name: Deploy Node.js app to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # 👇 your Azure Web App name (lowercase)
  AZURE_WEBAPP_NAME: citizen-engagement-app-mtn
  # We’re deploying the repo root because your package.json is at the root
  AZURE_WEBAPP_PACKAGE_PATH: .
  # Use Node 20.x
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-azure-deploy
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Build (TS → JS + client)
        run: npm run build
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZ
